name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
    { binding = "NOTES", id = "你在cf创建的kv空间第一个id" },
    { binding = "SHARE", id = "你在cf创建的kv空间第二个id" }
]
