name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"


kv_namespaces = [
  { binding = "NOTES", id = "你在cf创建的kv空间第一个id", preview_id = "01083e57f68046079a62015c3ea4a145" },
  { binding = "SHARE", id = "你在cf创建的kv空间第二个id", preview_id = "f89caa54860940709800dc6ed3ff920a" }
]

[env.production]
kv_namespaces = [
    { binding = "NOTES", id = "你在cf创建的kv空间第一个id" },
    { binding = "SHARE", id = "你在cf创建的kv空间第二个id" }
]
